services:
  web:
    build: .
    container_name: webserver
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ayden.lunnon
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet


volumes:
  db_data:

networks:
  webnet:
    driver: bridge